language: php

matrix:
  include:
  - php: 7.2
    env: WP_VERSION=latest WP_MULTISITE=0
  - php: 5.6
    env: WP_VERSION=nightly WP_MULTISITE=0
  - php: 5.6
    env: WP_TRAVISCI=phpcs

sudo: false

cache:
  directories:
  - vendor
  - "$HOME/.composer/cache"

install:
  - composer install

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      composer run set-config
    fi

script:
  - composer test
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      composer run lint
    fi

