language: php
php:
- 5.6
- 7.1
sudo: false
env:
- WP_VERSION=nightly WP_MULTISITE=0
- WP_VERSION=3.9 WP_MULTISITE=0

before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script: phpunit
